//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleCrud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lagu2
    {
        public int ID { get; set; }
        public string Artis { get; set; }
        public string StudioRekaman { get; set; }
        public string Judul { get; set; }
    }
}
